version: '3.8'

services:
  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - OLLAMA_MODEL=${OLLAMA_MODEL:-llama2}
      - OLLAMA_HOST=http://ollama:11434
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - ollama
    restart: unless-stopped
    networks:
      - mcp-network

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11435:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./docker/init-ollama.sh:/init-ollama.sh
    restart: unless-stopped
    entrypoint: ["sh", "/init-ollama.sh"]
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge

volumes:
  ollama_data: 